name: C Program Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Install dependencies (gcc, make, etc.)
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3. Compile the program
      - name: Build C program
        run: |
          gcc -o my_program main.c

      # 4. Run program (optional test)
      - name: Run program
        run: ./my_program

      # 5. Upload the compiled binary as an artifact (optional)
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: my_program
          path: ./my_program
