name: Super-Linter

on: 
  push

jobs:
  super-lint:
    name: Lint C code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # ✅ Enable only C linting
          VALIDATE_C: true
          VALIDATE_CPP: true

          # ❌ Disable all others to avoid noisy errors
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_JAVASCRIPT: false
